import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import {ThemeProvider} from "@/components/ThemeProvider";
// import { SideBox } from "@/components/side";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      
      <body className={inter.className}>
         <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
              <div className="container h-dvh  p-4">

        <Header />
        {/* <SideBox items={
        <div>
          <h1>Hello, World!</h1>
          <p>This is a sample content inside SideBox.</p>
        </div>
      } /> */}

        {children}
              </div>
      </ThemeProvider>
        
        </body>
    </html>
  );
}
